### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by bbugh** [123ishaTest/incremental-game-template#41]
Hi! :wave: Are you planning to publish this to NPM? Then it won't require copy and paste, and it can be updated easily. With rollup configured properly, it will tree shake, so only the code we use would get compiled. I would personally prefer being able to import it in the usual way. Thanks!

**Comment by Ishadijcks** [comment]
I wasn't planning on it. When using the template, you need to change the code in a few places. I figured an NPM package would only work if you would use it as a library, which isn't the case here.

The recommended way to use the template, is to fork it. You can still easily pull in updates and edits the scripts that way.

If you've used it a bit and still think an NPM package would be handy, I'll reconsider :slightly_smiling_face:

**Comment by bbugh** [comment]
Ah ha, thanks. I missed that while reading the docs.

**Comment by DylanSp** [comment]
> The recommended way to use the template, is to fork it. You can still easily pull in updates and edits the scripts that way.

Could you add this as a bit to the docs under the Introduction section (and maybe on the main site)? Right now, it's not clear how best to use this; I spent some time looking for an npm package before finding this issue.

**Comment by Ishadijcks** [comment]
Actually, I've changed my mind :sweat_smile:, here is the plan!

> Alright, after a great discussion with @dwhiffing#1470, we came to the following direction for the template:
> Package the script into a library, to make it easier to use in whatever application you'd like.
> 
> The user can then extend and override what is now `Game`, `Features` and `Achievements` for example.
> So you'd get something like this
> ```ts
> export class MyAchievements extends IgtAchievement {
>     initialize(myFeatures: MyFeatures) {
>         this.addAchievement(new MoneyAchievement(myFeatures.wallet));
>     }
> }
> ```
> We will get the repos
> - `igt-library` Typescript Code, well-tested npm package
> - `igt-docs` Describes the `igt-library`
> - `igt-vue` Vue project that uses the `igt-library` and renders it with a bunch of components. This is what most people can start with
> - `igt-demo` takes the `igt-template` and automatically applies the #tutorials to get to a demo application
> 
> **Pros**
> - No need to include the project files (tests, README, travis)
> - No more dummy content in the actual library
> - Things that are now TODO, can simply be abstract, forcing the user to fix them
> - Can even use the `igt-library` on a backend :eyes: 
> - No more forking/template problems as updates are managed by npm
> 
> **Cons**
> - Takes longer to get a running application. Should be offset by a much smaller learning curve
> - Developing the template becomes a bit more cumbersome as the UI is now separate
> 
> A rebranding might be needed, but I think this will make it much nicer to use :smiley:
> 
> Let me know if you have any thoughts :yum:

I will update the docs accordingly when it is finished.

**Comment by bbugh** [comment]
Sounds awesome!
